name: wawapp_driver
description: WawApp Driver Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.3
  intl: ^0.20.2
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4
  crypto: ^3.0.3
  firebase_messaging: ^15.2.10
  firebase_installations: ^2.0.0
  flutter_local_notifications: ^17.2.3
  firebase_analytics: ^11.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  enabled: true
  class_name: S
  main_locale: ar
  arb_dir: lib/l10n
  output_dir: lib/generated