name: wawapp_admin
description: WawApp Admin Panel - Web-based administration dashboard
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.3
  intl: ^0.20.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4
  cloud_functions: ^5.1.3
  firebase_analytics: ^11.3.3
  uuid: ^4.4.0
  http: ^0.13.6
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  auth_shared:
    path: ../../packages/auth_shared
  core_shared:
    path: ../../packages/core_shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
