name: wawapp_client
description: WawApp Client Application
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.3
  intl: ^0.20.2
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.0
  google_place: ^0.4.7
  uuid: ^4.4.0
  http: ^0.13.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.10
  permission_handler: ^11.3.1
  yaml: ^3.1.2
  crypto: ^3.0.3
  firebase_app_check: ^0.2.1
  flutter_secure_storage: ^9.0.0
  equatable: ^2.0.5

dev_dependencies:
  intl_utils: ^2.8.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  fake_cloud_firestore: ^2.4.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/wawapp_client_1024.png
  adaptive_icon_background: assets/icons/wawapp_client_adaptive_bg.png
  adaptive_icon_foreground: assets/icons/wawapp_client_1024.png

flutter_native_splash:
  color: "#0B1220"
  image: assets/icons/splash_client_logo.png
  android: true
  ios: true

flutter_intl:
  enabled: true
  class_name: S
  main_locale: ar
  arb_dir: lib/l10n
  output_dir: lib/generated