name: wawapp_client
description: WawApp Client Application
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.3
  intl: ^0.20.2
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.0
  google_place: ^0.4.7
  uuid: ^4.4.0
  http: ^0.13.6
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4
  crypto: ^3.0.3
  firebase_messaging: ^15.2.10
  firebase_analytics: ^11.3.3
  firebase_dynamic_links: ^6.1.10
  firebase_crashlytics: ^4.1.3
  package_info_plus: ^8.1.0
  auth_shared:
    path: ../../packages/auth_shared
  core_shared:
    path: ../../packages/core_shared
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.2.3
  yaml: ^3.1.2

dev_dependencies:
  intl_utils: ^2.8.6
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  mockito: ^5.4.4
  build_runner: ^2.4.8


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/wawapp_client_1024.png
  adaptive_icon_background: assets/icons/wawapp_client_adaptive_bg.png
  adaptive_icon_foreground: assets/icons/wawapp_client_1024.png

flutter_native_splash:
  color: "#0B1220"
  image: assets/icons/splash_client_logo.png
  android: true
  ios: true

flutter_intl:
  enabled: true
  class_name: S
  main_locale: ar
  arb_dir: lib/l10n
  output_dir: lib/generated